permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  pull-requests: write

name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: your-solution-name # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
      # Secret on repository level doesn't require to specify the environment name
      - run: echo repo-secret? ${{ secrets.repo_secret }}

      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Execute unit tests
        run: dotnet restore

      - name: Execute unit tests
        run: dotnet build --no-restore

      - run: mkdir ./reports

      - name: Execute unit tests
        run: dotnet test --results-directory ./reports --logger "trx;LogFileName=TestResults.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: tests
          path: ./reports/*.trx
          reporter: dotnet-trx

      # We liked dorny better for now, but EnricoMi may have more features
      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v2
      #   if: always()
      #   with:
      #     files: |
      #       ./reports/*.trx

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MSIX Package
          path: ./
