permissions:
  contents: read
  actions: read
  checks: write
  issues: read
  pull-requests: write

name: .NET Core Desktop

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on:
      ubuntu-latest # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    environment: test
    env:
      Solution_Name: your-solution-name # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Execute unit tests
        run: dotnet restore

      - name: Execute unit tests
        run: dotnet build --no-restore

      - run: mkdir ./reports

      - name: Execute unit tests
        run: dotnet test --results-directory ./reports --logger "trx;LogFileName=TestResults.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: tests
          path: ./reports/*.trx
          reporter: dotnet-trx

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MSIX Package
          path: ./
